# ==========================================
# Spring 核心變數設定
# ==========================================
spring:
  # 對應 XML 中的 <springProperty source="spring.application.name" ... />
  application:
    name: demo-springboot-ai

  # 對應 XML 中的 <springProfile name="dev"> 或 <springProfile name="prod">
  profiles:
    active: '@env.type@,@ai.type@' # 讓 Maven 打包時來替換這個值

  # 關閉網頁伺服器，並關閉 Spring 啟動的 ASCII 橫幅 (for MCP Server)
  main:
    web-application-type: none
    banner-mode: off

  # ==========================================
  # PostgreSQL 實體資料庫連線設定
  # ==========================================
  datasource:
    url: jdbc:postgresql://localhost:5433/rag_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10 # 企業級標準連線池設定

# ==========================================
# Line 設定
# ==========================================
line:
  token: ${TOKEN_LINE:} # 透過環境變數注入，冒號後面留空代表預設為空字串 (防呆，避免沒設 Token 時啟動報錯)
  api-url: https://api.line.me/v2/bot/message/push # API URL
  message-limit: 4000 # 單則訊息的字數最大限制為 5000 字，但為了安全起見，這裡設定為 4,000 字以避免超過限制導致發送失敗

# ==========================================
# Telegram 設定
# ==========================================
telegram:
  token: ${TOKEN_TELEGRAM:} # 透過環境變數注入，冒號後面留空代表預設為空字串 (防呆，避免沒設 Token 時啟動報錯)
  api-url: https://api.telegram.org/bot # API URL (前半段)
  send-url: /sendMessage # API URL (後半段)
  message-limit: 4000 # 單則訊息的字數最大限制

# ==========================================
# GitHub 設定
# ==========================================
github:
  username: emt2a7 # 我的 GitHub 帳號
  message-limit: 4000 # 單則訊息的字數最大限制
  god-token: ${TOKEN_GITHUB:} # 萬能金鑰，採用 Fine-grained PAT (細粒度金鑰)
  classic-token: ${TOKEN_GITHUB_CLASSIC:} # 傳統金鑰，採用 Classic PAT (傳統金鑰)
  base-url: https://api.github.com # GitHub API 的 Base URL
  all-repos-uri: /user/repos # 取得使用者所有 Repo 的 URI
  workflows-uri: /repos/${github.username}/{repo}/actions/workflows # 取得特定 Repo 的所有 Workflow 的 URI
  dispatches-uri: /repos/${github.username}/{repo}/actions/workflows/{workflow_id}/dispatches # 觸發 Workflow 的 URI
  runs-uri: /repos/${github.username}/{repo}/actions/runs # 查詢腳本執行狀態 (Workflow Runs)
  notifications-uri: /notifications # 查詢通知
  traffic-views-uri: /repos/${github.username}/{repo}/traffic/views # 查詢專案流量
  search-issues-uri: /search/issues # 查詢 Issue/PR

# ==========================================
# Tools 工具組設定
# ==========================================
rag:
  tools:
    hr: 請假、薪資、出差、員工福利、人資
    it: 智慧工廠、網路層、感知層、邊緣層、平台層、應用層、合勤(Zyxel)、巴魯夫(Balluff)、倍福(Beckhoff)、無線IO-Link、防火牆、HA、Switch、AI
    baby: 台灣人口、新生兒、出生率、生育率、死亡、女性

# ==========================================
# Logging 原生變數設定
# ==========================================
logging:
  # 控制各個套件的輸出層級 (會覆寫 XML 裡的 <root level="INFO">)
  level:
    root: INFO
    org.example: DEBUG # 讓您自己的程式碼印出詳細的 Debug 資訊
    org.springframework.ai: DEBUG # 開啟 Spring AI 的底層日誌，方便觀察與 Ollama 的連線
  file:
    path: D:/idea-worksapce/logs               # 對應 XML 的 LOG_PATH
    name: demo-springboot-cli      # 對應 XML 的 LOG_FILE_NAME

# ----------------------------------------------------------------------
# 　　　　【Bitfinex 設定】
# ----------------------------------------------------------------------
bitfinex:
  api:
    key: ddf2c62d58350f86bdcd626bf5a03bdee1ad73a9e63
    secret: 6d9ccb753b697b600e7b36a5364d07789bd8389b075
    algorithm: HmacSHA384 # 登入密碼的演算法
  webSocket:
    uri: wss://api.bitfinex.com/ws/2 # webStocket

