# 定義正式環境需要的配置
# ---------------------------------------------------------------------
# 　　　　【目錄設定】
# ---------------------------------------------------------------------
# kiosk 根目錄
kiosk:
  root: d:/kiosk3_prod
  home: ${kiosk.root}/kiosk_update_prod
  clear:
    db:
      enabled: N
    file:
      enabled: N
