# 定義開發環境需要的配置
# ---------------------------------------------------------------------
# 　　　　【目錄設定】
# ---------------------------------------------------------------------
# kiosk 根目錄
kiosk:
  root: d:/kiosk3
  home: ${kiosk.root}/kiosk_update
  clear:
    db:
      enabled: Y
    file:
      enabled: Y
