# ==========================================
# Spring 核心變數設定
# ==========================================
spring:
  # 對應 XML 中的 <springProperty source="spring.application.name" ... />
  application:
    name: demo-springboot-ai

  # 對應 XML 中的 <springProfile name="dev"> 或 <springProfile name="prod">
  profiles:
    active: '@env.type@,@ai.type@' # 讓 Maven 打包時來替換這個值

  # 關閉網頁伺服器，並關閉 Spring 啟動的 ASCII 橫幅 (for MCP Server)
  main:
    web-application-type: none
    banner-mode: off

  # ==========================================
  # PostgreSQL 實體資料庫連線設定
  # ==========================================
  datasource:
    url: jdbc:postgresql://localhost:5433/rag_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10 # 企業級標準連線池設定

# ==========================================
# Telegram 設定
# ==========================================
telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN:} # 透過環境變數注入，冒號後面留空代表預設為空字串 (防呆，避免沒設 Token 時啟動報錯)
  bot-url-root: https://api.telegram.org/bot # Telegram Bot API 的基礎 URL
  bot-url-send: /sendMessage # Telegram Bot API 的發送訊息路徑
  test-github-token: ${MY_GITHUB_TOKEN:} # 測試用的 Git

# ==========================================
# Tools 工具組設定
# ==========================================
rag:
  tools:
    hr: 請假、薪資、出差、員工福利、人資
    it: 智慧工廠、網路層、感知層、邊緣層、平台層、應用層、合勤(Zyxel)、巴魯夫(Balluff)、倍福(Beckhoff)、無線IO-Link、防火牆、HA、Switch、AI
    baby: 台灣人口、新生兒、出生率、生育率、死亡、女性

# ==========================================
# Logging 原生變數設定
# ==========================================
logging:
  # 控制各個套件的輸出層級 (會覆寫 XML 裡的 <root level="INFO">)
  level:
    root: INFO
    org.example: DEBUG # 讓您自己的程式碼印出詳細的 Debug 資訊
    org.springframework.ai: DEBUG # 開啟 Spring AI 的底層日誌，方便觀察與 Ollama 的連線
  file:
    path: D:/idea-worksapce/logs               # 對應 XML 的 LOG_PATH
    name: demo-springboot-cli      # 對應 XML 的 LOG_FILE_NAME

# ----------------------------------------------------------------------
# 　　　　【Bitfinex 設定】
# ----------------------------------------------------------------------
bitfinex:
  api:
    key: ddf2c62d58350f86bdcd626bf5a03bdee1ad73a9e63
    secret: 6d9ccb753b697b600e7b36a5364d07789bd8389b075
    algorithm: HmacSHA384 # 登入密碼的演算法
  webSocket:
    uri: wss://api.bitfinex.com/ws/2 # webStocket

