package org.example.framework.repository;

import org.example.framework.entity.AuthUser;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.test.context.ActiveProfiles;

import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@ActiveProfiles("test") // 🌟 加上這行：宣告目前是 test 環境
class AuthUserRepositoryTest {

    @Autowired
    private AuthUserRepository authUserRepository;

    @Test
    void testSaveAndFindById() {
        AuthUser user = AuthUser.builder()
                .name("張三")
                .age(30)
                .createUser("system")
                .build();

        AuthUser saved = authUserRepository.save(user);
        assertThat(saved.getId()).isNotNull();

        Optional<AuthUser> found = authUserRepository.findById(saved.getId());
        assertThat(found).isPresent();
        assertThat(found.get().getName()).isEqualTo("張三");
        assertThat(found.get().getAge()).isEqualTo(30);
    }

    @Test
    void testNameUniqueConstraint() {
        AuthUser user1 = AuthUser.builder()
                .name("李四")
                .age(30)
                .createUser("system")
                .build();
        authUserRepository.saveAndFlush(user1);

        AuthUser user2 = AuthUser.builder()
                .name("李四")
                .age(25)
                .createUser("system")
                .build();

        assertThatThrownBy(() -> authUserRepository.saveAndFlush(user2))
                .isInstanceOf(DataIntegrityViolationException.class);
    }

    @Test
    void testCreationTimestampAutoGenerated() {
        AuthUser user = AuthUser.builder()
                .name("王五")
                .age(28)
                .createUser("system")
                .build();

        AuthUser saved = authUserRepository.save(user);
        authUserRepository.flush();

        assertThat(saved.getCreateTime()).isNotNull();
    }

    @Test
    void testUpdateTimestampAutoUpdated() throws InterruptedException {
        AuthUser user = AuthUser.builder()
                .name("趙六")
                .age(35)
                .createUser("system")
                .build();

        AuthUser saved = authUserRepository.saveAndFlush(user);
        // 🌟 修正1：初始新增時，updateTime 就已經有值了
        assertThat(saved.getUpdateTime()).isNotNull();
        java.time.OffsetDateTime initialUpdateTime = saved.getUpdateTime();

        // 強制讓執行緒睡 10 毫秒，確保等等更新的時間一定會晚於初始時間
        Thread.sleep(10);

        saved.setAge(36);
        saved.setUpdateUser("admin");
        AuthUser updated = authUserRepository.saveAndFlush(saved);

        // 🌟 修正2：驗證更新後的時間，確實晚於初始時間
        assertThat(updated.getUpdateTime()).isAfter(initialUpdateTime);
    }

    @Test
    void testAuditFieldsConstraints() throws InterruptedException {
        AuthUser user = AuthUser.builder()
                .name("孫七")
                .age(40)
                .createUser("system")
                .build();

        AuthUser saved = authUserRepository.saveAndFlush(user);
        assertThat(saved.getCreateTime()).isNotNull();
        // 🌟 修正1：初始新增時，updateTime 就已經有值了
        assertThat(saved.getUpdateTime()).isNotNull();

        java.time.OffsetDateTime initialCreateTime = saved.getCreateTime();
        java.time.OffsetDateTime initialUpdateTime = saved.getUpdateTime();

        Thread.sleep(10);

        saved.setAge(41);
        saved.setUpdateUser("admin");
        AuthUser updated = authUserRepository.saveAndFlush(saved);

        // 🌟 修正2：CreateTime 不變，UpdateTime 變晚
        assertThat(updated.getCreateTime()).isEqualTo(initialCreateTime);
        assertThat(updated.getUpdateTime()).isAfter(initialUpdateTime);
    }
}
