name: 【🚀 AI助理】發布至「開發+OpenAI」環境

on:
  workflow_dispatch:                                      # 觸發時機：手動觸發

jobs:
  call-super-build:                                       # Job名稱：call-super-build
    uses: ./.github/workflows/build-super-agent.yml       # 載入共用模組 Workflow 定義檔
    with:                                                 # 傳入參數
      job_name: "Build Native CLI"                        # - 參數名稱
      maven_profiles: "dev,openai"                        # - 參數名稱
      artifact_name: "Demo-SpringBoot-CLI"                # - 參數名稱
