name: ✅【執行】正式環境(Prod)

on:
  workflow_dispatch:
    inputs:
      source_platform:                                                      # 定義傳入的參數
        description: '平台來源：line、telegram (全小寫)'                        # - 參數說明
        required: false                                                     # - 參數是否必填
        type: string                                                        # - 參數類型
        default: ''                                                         # - 參數預設值 (預設空字串)
      chat_id:                                                              # 定義傳入的參數
        description: 'line、telegram 的 ID (5015499247)'                     # - 參數說明
        required: false                                                     # - 參數是否必填
        type: string                                                        # - 參數類型
        default: ''                                                         # - 參數預設值 (預設空字串)
      user_prompt:                                                          # 定義傳入的參數
        description: '使用者提示詞 (Prompt)'                                  # - 參數說明
        required: true                                                      # - 參數是否必填
        type: string                                                        # - 參數類型
        default: '明天桃園市天氣溫度如何？'                                      # - 參數預設值

jobs:                                                 # 工作流程
  run-cli:                                            # Job名稱：run-cli
    permissions:                                      # 明確賦予呼叫共用模組所需的權限
      actions: read
      contents: read

    uses: ./.github/workflows/module-exec.yml       # 呼叫共用模組時，路徑必須相對於專案根目錄
    with:
      source_platform: ${{ inputs.source_platform }}  # 輸入參數：平台來源：line、telegram (全小寫)
      chat_id: ${{ inputs.chat_id }}                  # 輸入參數：line、telegram 的 ID
      user_prompt: ${{ inputs.user_prompt }}          # 輸入參數：使用者提示詞 (Prompt)
      download_type: 'release'                        # 輸入參數：下載來源 (填寫 "artifact" 或 "release")
      release_pattern: 'demo-springboot-cli'          # 輸入參數：「執行檔」的實體檔名 (僅在 download_type 為 release 時有效)
      summary_title: '### 🤖 AI 助理的回覆 (正式版本)'   # 輸入參數：GitHub Step Summary 顯示的標題
    secrets: inherit                                  # 讓「被呼叫端(module-deploy.yml)」繼承「呼叫端(exe-prod-agent.yml)」的所有 secrets