name: 👷 手動執行「開發」環境

on:
  workflow_dispatch:
    inputs:
      user_prompt:
        description: '請輸入你要讓 AI 執行的指令或問題：'
        required: true
        default: '幫我總結 Spring Boot AOT 的優點'

jobs:                                                 # 工作流程
  run-cli:                                            # Job名稱：run-cli
    uses: ./.github/workflows/run-shared-module.yml   # 呼叫共用模組時，路徑必須相對於專案根目錄
    with:
      user_prompt: ${{ inputs.user_prompt }}          # 輸入參數：提示詞 (Prompt)
      download_type: 'artifact'                       # 輸入參數：下載來源 (填寫 "artifact" 或 "release")
      artifact_name: 'Demo-SpringBoot-CLI-Dev'        # 輸入參數：Artifact 名稱 (僅在 download_type 為 artifact 時有效)
      summary_title: '### 🤖 AI 助理的回覆 (開發版本)'   # 輸入參數：GitHub Step Summary 顯示的標題
    secrets: inherit                                  # 確保共用模組能繼承並使用 GITHUB_TOKEN
